trigger:
  branches:
    include:
      - main # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Production'
  buildDir: 'dist/<your-angular-app-name>' # Replace with your Angular app folder name

stages:
- stage: Build
  displayName: Build Angular Application
  jobs:
  - job: Build
    displayName: Build Angular App
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x' # Ensure this matches the Node.js version required for Angular
      displayName: Use Node.js

    - script: |
        set -x
        echo "Installing Angular CLI globally..."
        npm install -g @angular/cli || exit 3
        echo "Installing project dependencies..."
        npm install || exit 3
        echo "Building Angular application..."
        ng build --configuration $(buildConfiguration) || exit 3

        echo "Validating build output directory..."
        if [ ! -d "$(System.DefaultWorkingDirectory)/$(buildDir)" ]; then
          echo "Error: Build output directory does not exist."
          exit 3
        fi
      displayName: Install and Build Angular App

    - script: |
        echo "Listing build output directory contents:"
        ls -la $(System.DefaultWorkingDirectory)/$(buildDir)
      displayName: Verify Build Output

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/$(buildDir)
        artifact: angular-app
        publishLocation: pipeline
      displayName: Publish Build Artifacts

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy Angular App to Azure
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'serviceconnection' # Replace with your Azure service connection name
        appType: 'webAppLinux' # Use 'webAppWindows' if your app is on a Windows App Service
        appName: 'nextopswebappservices' # Replace with your Azure Web App name
        package: $(Pipeline.Workspace)/angular-app
      displayName: Deploy Application to Azure
