trigger:
  branches:
    include:
      - main # Replace with your branch name if different

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Production'
  buildDir: 'D:\Angular\dist\browser' # Relative path to the build output directory inside the project

stages:
- stage: Build
  displayName: Build Angular Application
  jobs:
  - job: Build
    displayName: Build Angular App
    steps:
    # Use Node.js version 20.0.0
    - task: NodeTool@0
      inputs:
        versionSpec: '20.0.0' # Updated to Node.js 20.0.0
      displayName: Use Node.js 20.0.0

    # Validate environment
    - script: |
        set -eux
        echo "Verifying environment..."
        echo "Node.js Version:"
        node -v
        echo "NPM Version:"
        npm -v
        echo "Installing Angular CLI globally..."
        npm install -g @angular/cli
      displayName: Validate Environment

    # Install dependencies and build the application
    - script: |
        set -eux
        echo "Installing project dependencies..."
        rm -rf node_modules
        npm install
        
        echo "Building Angular application..."
        ng build --configuration $(buildConfiguration)
        
        echo "Validating build output directory..."
        if [ ! -d "$(System.DefaultWorkingDirectory)/$(buildDir)" ]; then
          echo "Error: Build output directory $(buildDir) does not exist."
          exit 3
        fi
      displayName: Install and Build Angular App

    # Verify build output directory contents
    - script: |
        echo "Listing build output directory contents:"
        ls -la $(System.DefaultWorkingDirectory)/$(buildDir)
      displayName: Verify Build Output

    # Publish build artifacts
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/$(buildDir)
        artifact: angular-app
        publishLocation: pipeline
      displayName: Publish Build Artifacts

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy Angular App to Azure
    steps:
    # Deploy build artifacts to Azure App Service
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'azure@serviceconnection123' # Replace with your Azure service connection name
        appType: 'webAppLinux' # Change to 'webAppWindows' if using Windows App Services
        appName: 'nextopswebappservices' # Replace with your Azure Web App name
        package: $(Pipeline.Workspace)/angular-app
      displayName: Deploy Application to Azure
